### ISSUE TITLE
cant get mail part working

### ISSUE THREAD

**Issue by timmhcdk** [Apoc70/Purge-LogFiles#1]
error From EMS# (running in elevated mode )
If -SendMail specified, -MailFrom, -MailTo and -MailServer must be specified as well!
At C:\scripts\Purge-LogFiles1.7.ps1:182 char:5
-     Throw "If -SendMail specified, -MailFrom, -MailTo and -MailServer must be sp ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : OperationStopped: (If -SendMail sp...cified as well!:String) [], RuntimeException
  - FullyQualifiedErrorId : If -SendMail specified, -MailFrom, -MailTo and -MailServer must be specified as well!

------from script--------

[parameter(Mandatory=$false,ValueFromPipeline=$false,HelpMessage='Number of days for log files retention')][int]$DaysToKeep = 14,  
    [parameter(Mandatory=$false,ValueFromPipeline=$false,HelpMessage='Use automatic folder detection for Exchange and IIS log paths')][switch]$Auto,
    [parameter(Mandatory=$false,ValueFromPipeline=$false,HelpMessage='Send result summary as email')][switch]$SendMail,
    [parameter(Mandatory=$false,ValueFromPipeline=$false,HelpMessage='Sender address for result summary')][string]$MailFrom = "mymail@adr.com"",
    [parameter(Mandatory=$false,ValueFromPipeline=$false,HelpMessage='Recipient address for result summary')][string]$MailTo = "mymail@adr.com",
    [parameter(Mandatory=$false,ValueFromPipeline=$false,HelpMessage='SMTP Server address for sending result summary')][string]$MailServer = "mymail.server.com"

mymail.server.com= my smtp host
mymail@adr.com= my mail adress reciver and sender 

What am i missing ??

**Comment by Apoc70** [comment]
Hi,
Which PowerShell version are you using to run the script?

**Comment by timmhcdk** [comment]
sorry my bad i was executeing the script wrong must use scriptname -sendmail thanks :D
