### ISSUE TITLE
SendMail switch is set by default

### ISSUE THREAD

**Issue by jazzl0ver** [Apoc70/Purge-LogFiles#7]
```
PS C:\Utils> .\Purge-LogFiles.ps1 -DaysToKeep 60 -Auto
If -SendMail specified, -MailFrom, -MailTo and -MailServer must be specified as well!
At C:\Utils\Purge-LogFiles.ps1:346 char:5
+     Throw 'If -SendMail specified, -MailFrom, -MailTo and -MailServer ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (If -SendMail sp...cified as well!:String) [], RuntimeException
    + FullyQualifiedErrorId : If -SendMail specified, -MailFrom, -MailTo and -MailServer must be specified as well!
```

**Comment by Apoc70** [comment]
Thanks for the update.

**Comment by jazzl0ver** [comment]
Were you able to get that fixed? I've just grabbed the latest version and it still throws that error

**Comment by Apoc70** [comment]
What is the system configuration where you are receiving the error? The SendMail switch is not set to $true by default.

When testing on Windows Server 2012R2 and Exchange 2013/2016 I do not encounter any issues.

**Comment by oliverweidel** [comment]
Please note, that everybody in this list is receiving this emails...

Am 11.10.2017 15:27 schrieb Thomas Stensitzki <notifications@github.com>:

What is the system configuration where you are receiving the error? The SendMail switch is not set to $true by default.

**Comment by jazzl0ver** [comment]
@Apoc70 my system is Windows Server 2016 with Exchange Server 2016 installed.
